CREATE USER 'logis'@'localhost' IDENTIFIED BY 'YmYaeStUYQ7PLN3A'; GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, LOCK TABLES, 
CREATE VIEW, EXECUTE ON *.* TO 'logis'@'localhost' IDENTIFIED BY 'YmYaeStUYQ7PLN3A' 
WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;